#include <stdio.h>

get_new_dict_full (int size_hint);
int _gf_msg (const char *domain, const char *file,;
extern int pthread_mutex_lock (pthread_mutex_t *__mutex);
dict_lookup_common (dict_t *this, char *key);
extern int pthread_mutex_unlock (pthread_mutex_t *__mutex);
dict_set_lk (dict_t *this, char *key, data_t *value, gf_boolean_t replace);
uint32_t SuperFastHash (const char * data, int32_t len) {;
extern size_t strlen (const char *__s);
extern int strcmp (const char *__s1, const char *__s2);
data_unref (data_t *this);
__gf_free (void *free_ptr);
mem_put (void *ptr);
extern int pthread_mutex_destroy (pthread_mutex_t *__mutex);
extern void free (void *__ptr) __attribute__ ((__nothrow__ , __leaf__));;
extern int *__errno_location (void) __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__const__));;
dict_get_with_ref (dict_t *this, char *key, data_t **data);
data_to_int8_ptr (data_t *data, int8_t *val);
data_from_int8 (int8_t value);
data_destroy (data_t *data);
data_to_int16_ptr (data_t *data, int16_t *val);
data_from_int16 (int16_t value);
data_to_int32_ptr (data_t *data, int32_t *val);
data_from_int32 (int32_t value);
data_to_int64_ptr (data_t *data, int64_t *val);
data_from_int64 (int64_t value);
data_to_uint16_ptr (data_t *data, uint16_t *val);
data_from_uint16 (uint16_t value);
data_to_uint32_ptr (data_t *data, uint32_t *val);
data_from_uint32 (uint32_t value);
data_to_uint64_ptr (data_t *data, uint64_t *val);
data_from_uint64 (uint64_t value);
data_to_double_ptr (data_t *data, double *val);
data_from_double (double value);
data_from_ptr_common (void *value, gf_boolean_t is_static);
data_from_dynptr (void *value, int32_t len);
data_to_ptr_common (data_t *data, void **val);
str_to_data (char *value);
char * gf_strdup (const char *src);
data_from_dynstr (char *value);
dict_set_bin_common (dict_t *this, char *key, void *ptr, size_t size,;
gf_string2boolean (const char *str, gf_boolean_t *b);
dict_serialized_length_lk (dict_t *this);
dict_serialize_lk (dict_t *this, char *buf);
extern void *memcpy (void *__restrict __dest, const void *__restrict __src,;
get_new_data ();
memdup (const void *ptr, size_t size);
__gf_calloc (size_t nmemb, size_t size, uint32_t type, const char *typestr);
dict_serialize_value_with_delim_lk (dict_t *this, char *buf, int32_t *serz_len,;
extern int snprintf (char *__restrict __s, size_t __maxlen,;
void _gf_proc_dump_build_key (char *key, const char *prefix, char *fmt,...);
gf_proc_dump_write (char *key, char *value, ...);
mem_get0 (struct mem_pool *mem_pool);
__glusterfs_this_location ();
extern int pthread_mutex_init (pthread_mutex_t *__mutex,;
_gf_msg_backtrace_nomem (gf_loglevel_t level, int stacksize);
__attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__nonnull__ (1, 2))) __attribute__ ((__deprecated__));;
gf_asprintf (char **string_ptr, const char *format, ...);
data_ref (data_t *this);
extern char *strcpy (char *__restrict __dest, const char *__restrict __src);
__is_member (struct mem_pool *pool, void *ptr);
list_add (struct list_head *new, struct list_head *head);
extern void abort (void) __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__noreturn__));;
extern long int strtol (const char *__restrict __nptr,;
extern long long int strtoll (const char *__restrict __nptr,;
extern unsigned long int strtoul (const char *__restrict __nptr,;
extern unsigned long long int strtoull (const char *__restrict __nptr,;
extern double strtod (const char *__restrict __nptr,;
bin_to_data (void *value, int32_t len);
extern int strcasecmp (const char *__s1, const char *__s2);
__gf_malloc (size_t size, uint32_t type, const char *typestr);
void* __gf_default_calloc (int cnt, size_t size);
extern void *calloc (size_t __nmemb, size_t __size);
_gf_msg_nomem (const char *domain, const char *file,;
gf_mem_set_acct_info (xlator_t *xl, char **alloc_ptr, size_t size,;
extern void *memset (void *__s, int __c, size_t __n) __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__nonnull__ (1)));;
extern int vsnprintf (char *__restrict __s, size_t __maxlen,;
gf_proc_dump_write_strfd (char *key, char *value, va_list ap);
gf_proc_dump_write_fd (char *key, char *value, va_list ap);
mem_get (struct mem_pool *mem_pool);
extern void *pthread_getspecific (pthread_key_t __key) __attribute__ ((__nothrow__ , __leaf__));;
extern int pthread_setspecific (pthread_key_t __key,;
extern int fileno (FILE *__stream) __attribute__ ((__nothrow__ , __leaf__)) ;;
gf_vasprintf (char **string_ptr, const char *format, va_list arg);
void* __gf_default_malloc (size_t size);
extern void *malloc (size_t __size) __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__malloc__)) ;;
extern char *strrchr (const char *__s, int __c);
extern int gettimeofday (struct timeval *__restrict __tv,;
gf_time_fmt (char *dst, size_t sz_dst, time_t utime, unsigned int fmt);
extern void syslog (int __pri, const char *__fmt, ...);
sys_write (int fd, const void *buf, size_t count);
int strprintf(strfd_t *strfd, const char *fmt, ...);
strvprintf (strfd_t *strfd, const char *fmt, va_list ap);
list_del (struct list_head *old);
_gf_timestuff (gf_timefmts *fmt, const char ***fmts, const char ***zeros);
extern struct tm *gmtime_r (const time_t *__restrict __timer,;
extern size_t strftime (char *__restrict __s, size_t __maxsize,;
extern char *strncpy (char *__restrict __dest,;
strfd_close (strfd_t *strfd);
extern int vasprintf (char **__restrict __ptr, const char *__restrict __f,;
gf_roundup_next_power_of_two (int32_t nr);
__gf_realloc (void *ptr, size_t size);
void* __gf_default_realloc (void *oldptr, size_t size);
extern void *realloc (void *__ptr, size_t __size);
